# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chassis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchassis.proto\x12\tcomm_data\"\x89\x02\n\x07\x43hassis\x12\x1d\n\x04gear\x18\x01 \x01(\x0e\x32\x0f.comm_data.Gear\x12\x15\n\rthrottle_rate\x18\x02 \x01(\x01\x12\x12\n\nbreak_rate\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x05 \x01(\x01\x12\r\n\x05\x61ngle\x18\x06 \x01(\x01\x12\x16\n\x0esteering_theta\x18\x07 \x01(\x01\x12\x17\n\x0fsteering_dtheta\x18\x08 \x01(\x01\x12\x1e\n\x16steering_rotaion_speed\x18\t \x01(\x01\x12\x10\n\x08gear_num\x18\n \x01(\x03\x12\x1d\n\x15motor_middle_position\x18\x0b \x01(\x01*\"\n\x04Gear\x12\x05\n\x01\x44\x10\x00\x12\x05\n\x01R\x10\x01\x12\x05\n\x01P\x10\x02\x12\x05\n\x01N\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chassis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GEAR._serialized_start=296
  _GEAR._serialized_end=330
  _CHASSIS._serialized_start=29
  _CHASSIS._serialized_end=294
# @@protoc_insertion_point(module_scope)
