# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chassis_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import chassis_pb2 as chassis__pb2
import header_pb2 as header__pb2
import motor_error_info_pb2 as motor__error__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hassis_info.proto\x12\tcomm_data\x1a\rchassis.proto\x1a\x0cheader.proto\x1a\x16motor_error_info.proto\"\x7f\n\rChassisStatus\x12\x1e\n\x16motor_electric_current\x18\x01 \x01(\x01\x12\x19\n\x11is_motor_overtake\x18\x02 \x01(\x08\x12\x33\n\x10motor_error_info\x18\x03 \x01(\x0b\x32\x19.comm_data.MotorErrorInfo\"\x7f\n\x0b\x43hassisInfo\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.comm_data.Header\x12#\n\x07\x63hassis\x18\x02 \x01(\x0b\x32\x12.comm_data.Chassis\x12(\n\x06status\x18\x03 \x01(\x0b\x32\x18.comm_data.ChassisStatusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chassis_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHASSISSTATUS._serialized_start=86
  _CHASSISSTATUS._serialized_end=213
  _CHASSISINFO._serialized_start=215
  _CHASSISINFO._serialized_end=342
# @@protoc_insertion_point(module_scope)
